default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch("RAILS_DATABASE_USERNAME") { 'postgres' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: cinema_development
test:
  <<: *default
  database: cinema_test
production:
  <<: *default
  database: cinema_production
  # ENV[] does not raise any exception if the key is not found.
  host:     <%= ENV['PRODUCTION_DATABASE_HOSTNAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
